### ISSUE TITLE
error when running 09_2_softmax_mnist.py

### ISSUE THREAD

**Issue by cxy19941228** [hunkim/PyTorchZeroToAll#11]
Traceback (most recent call last):
  File "/home/cxy/chenxiuyi/PyTorchZeroToAll/09_2_softmax_mnist.py", line 94, in <module>
    test()
  File "/home/cxy/chenxiuyi/PyTorchZeroToAll/09_2_softmax_mnist.py", line 81, in test
    test_loss += criterion(output, target, size_average=False).data[0]
  File "/home/cxy/anaconda2/envs/conda_conda_torch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'size_average'

So I use "test_loss += criterion(output,target).data[0]". It's ok! I want to know why you use "size_average=False".

Best regards

**Comment by cxy19941228** [comment]
also in 08_2_dataset_loade_logistic.py. The line 15, I think, is misspelled. The path is "./data/diabetes.csv.gz"  instead of 'data-diabetes.csv'.

**Comment by hunkim** [comment]
Thanks! It's now fixed. Also, let me know if you find more errors.
