### ISSUE TITLE
RuntimeError: dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by jiapei100** [hunkim/PyTorchZeroToAll#24]
line 78 of 12_2_hello_rnn.py 
What's wrong with it? `loss += criterion(output, label)`

> $ python 12_2_hello_rnn.py
> Model(
>   (rnn): RNN(5, 5, batch_first=True)
> )
> predicted string: lTraceback (most recent call last):
>   File "12_2_hello_rnn.py", line 78, in <module>
>     loss += criterion(output, label)
>   File "/home/jiapei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jiapei/.local/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 759, in forward
>     self.ignore_index, self.reduce)
>   File "/home/jiapei/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1442, in cross_entropy
>     return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
>   File "/home/jiapei/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1328, in nll_loss
>     if input.size(0) != target.size(0):
> RuntimeError: dimension specified as 0 but tensor has no dimensions

**Comment by wbaik** [comment]
I ran into the same issue, guessing this happened from a recent update in `pytorch` .
A solution, though I am sure there this is not the best way, was adding this before `line 78`
``` label = label.unsqueeze(0) ```

**Comment by lauraliu61b** [comment]
I guess another possible solution is to replace the original label at line 78 with torch.LongTensor([label]).
