### ISSUE TITLE
Error on 10_1_cnn_mnist.py

### ISSUE THREAD

**Issue by jianlianggao** [hunkim/PyTorchZeroToAll#41]
Hi Prof. Kim

When I ran 10_1_cnn_mnist.py on Python 3.5 (Ubuntu 16.04.5 LTS), I met the following error:

10_1_cnn_mnist.py:49: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.log_softmax(x)
Traceback (most recent call last):
  File "10_1_cnn_mnist.py", line 92, in <module>
    train(epoch)
  File "10_1_cnn_mnist.py", line 69, in train
    100. * batch_idx / len(train_loader), loss.data[0]))
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

Look forward to hearing from soon. Many thanks,
Jianliang

**Comment by jianlianggao** [comment]
I fixed the issue now by changing loss.data[0] to float(loss)
